---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openshift-monitoring-controllers
spec:
  serviceAccountName: flux-infra
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/openshift-monitoring/controllers/${ENVIRONMENT}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openshift-monitoring-configs
spec:
  serviceAccountName: flux-infra
  dependsOn:
    - name: openshift-monitoring-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-infra
  path: components/openshift-monitoring/configs/${ENVIRONMENT}
