apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-test
resources:
  - namespace.yaml
  - rbac.yaml
  - sync.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: apps
      app.kubernetes.io/component-name: app-test